name: jokes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.3.3
  dartz: ^0.10.1
  dev: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  http: ^0.13.6
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.7
  freezed: ^2.4.1
  json_serializable: ^6.6.2



flutter:
  uses-material-design: true


  assets:
    - assets/lottie/
